apiVersion: apps/v1
kind: Deployment
metadata:
  name: volund-web
  labels:
    app: volund-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: volund-web
  template:
    metadata:
      labels:
        app: volund-web
    spec:
      containers:
        - name: web
          image: ghcr.io/ai-volund/volund-web
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 10m
              memory: 32Mi
            limits:
              cpu: 100m
              memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: volund-web
spec:
  selector:
    app: volund-web
  ports:
    - port: 80
      targetPort: 80
